/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nacionaudiovisual.gui;

import java.awt.Color;

/**
 *
 * @author alexa
 */
public class registration_form extends javax.swing.JFrame {

    /**
     * Creates new form registration_form
     */
    int xMouse, yMouse;
    public registration_form() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgruondPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        nacionaudiovisual = new javax.swing.JLabel();
        txtIdentifyNumber = new javax.swing.JTextField();
        coperyng = new javax.swing.JLabel();
        txtDue = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        txtYearsold = new javax.swing.JTextField();
        cellphone = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        identifynumber = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        yearsold = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        password = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtCellphone = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnRegistration = new javax.swing.JPanel();
        btnRegister = new javax.swing.JLabel();
        btnBAck = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        scrollbar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        backgruondPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name:");
        backgruondPanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        nacionaudiovisual.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nacionaudiovisual.setForeground(new java.awt.Color(255, 255, 255));
        nacionaudiovisual.setText("Personal Information");
        backgruondPanel.add(nacionaudiovisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 120, -1));

        txtIdentifyNumber.setBackground(new java.awt.Color(70, 100, 109));
        txtIdentifyNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdentifyNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtIdentifyNumber.setBorder(null);
        backgruondPanel.add(txtIdentifyNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 150, 30));

        coperyng.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        coperyng.setForeground(new java.awt.Color(255, 255, 255));
        coperyng.setText("@Coperyng 2023");
        backgruondPanel.add(coperyng, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        txtDue.setBackground(new java.awt.Color(70, 100, 109));
        txtDue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDue.setForeground(new java.awt.Color(255, 255, 255));
        txtDue.setBorder(null);
        backgruondPanel.add(txtDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 150, 30));

        txtLastName.setBackground(new java.awt.Color(70, 100, 109));
        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setBorder(null);
        backgruondPanel.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 150, 30));

        lastname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lastname.setForeground(new java.awt.Color(255, 255, 255));
        lastname.setText("Lastname:");
        backgruondPanel.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        txtYearsold.setBackground(new java.awt.Color(70, 100, 109));
        txtYearsold.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtYearsold.setForeground(new java.awt.Color(255, 255, 255));
        txtYearsold.setText(" ");
        txtYearsold.setBorder(null);
        backgruondPanel.add(txtYearsold, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, 30));

        cellphone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cellphone.setForeground(new java.awt.Color(255, 255, 255));
        cellphone.setText("Cellphone Number:");
        backgruondPanel.add(cellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));
        backgruondPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 150, 10));
        backgruondPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, 10));
        backgruondPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 150, 10));

        identifynumber.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        identifynumber.setForeground(new java.awt.Color(255, 255, 255));
        identifynumber.setText("Identify Number:");
        backgruondPanel.add(identifynumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));
        backgruondPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 150, 10));

        yearsold.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yearsold.setForeground(new java.awt.Color(255, 255, 255));
        yearsold.setText("Years Old:");
        backgruondPanel.add(yearsold, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        txtAdress.setBackground(new java.awt.Color(70, 100, 109));
        txtAdress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAdress.setForeground(new java.awt.Color(255, 255, 255));
        txtAdress.setText(" ");
        txtAdress.setBorder(null);
        backgruondPanel.add(txtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 150, 30));

        txtName.setBackground(new java.awt.Color(70, 100, 109));
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        backgruondPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, 30));

        txtPassword.setBackground(new java.awt.Color(70, 100, 109));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        backgruondPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 150, 30));
        backgruondPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 150, -1));

        password.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");
        backgruondPanel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name:");
        backgruondPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adress:");
        backgruondPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));
        backgruondPanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 150, 10));

        txtCellphone.setBackground(new java.awt.Color(70, 100, 109));
        txtCellphone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCellphone.setForeground(new java.awt.Color(255, 255, 255));
        txtCellphone.setText(" ");
        txtCellphone.setBorder(null);
        backgruondPanel.add(txtCellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 150, 30));
        backgruondPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 150, -1));
        backgruondPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, 10));

        btnRegistration.setBackground(new java.awt.Color(237, 111, 113));
        btnRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrationMouseExited(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("       Register");

        javax.swing.GroupLayout btnRegistrationLayout = new javax.swing.GroupLayout(btnRegistration);
        btnRegistration.setLayout(btnRegistrationLayout);
        btnRegistrationLayout.setHorizontalGroup(
            btnRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
        );
        btnRegistrationLayout.setVerticalGroup(
            btnRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        backgruondPanel.add(btnRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 120, 30));

        btnBAck.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBAck.setForeground(new java.awt.Color(255, 255, 255));
        btnBAck.setText("  back");
        btnBAck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBAckMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBAckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBAckMouseExited(evt);
            }
        });
        backgruondPanel.add(btnBAck, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 50, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nacionaudiovisual/imagesBackground/registration_form_1.png"))); // NOI18N
        backgruondPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        scrollbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                scrollbarMouseDragged(evt);
            }
        });
        scrollbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                scrollbarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout scrollbarLayout = new javax.swing.GroupLayout(scrollbar);
        scrollbar.setLayout(scrollbarLayout);
        scrollbarLayout.setHorizontalGroup(
            scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        scrollbarLayout.setVerticalGroup(
            scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        backgruondPanel.add(scrollbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgruondPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgruondPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scrollbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollbarMouseDragged
        int x = evt.getXOnScreen()-xMouse;
        int y = evt.getYOnScreen()-yMouse;
        this.setLocation(x, y);
    }//GEN-LAST:event_scrollbarMouseDragged

    private void scrollbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_scrollbarMousePressed

    private void btnBAckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBAckMouseEntered
        btnBAck.setForeground(Color.red);
    }//GEN-LAST:event_btnBAckMouseEntered

    private void btnBAckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBAckMouseExited
        btnBAck.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBAckMouseExited

    private void btnBAckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBAckMouseClicked
        main_login backmain = new main_login();
        this.dispose();
        backmain.setVisible(true);
    }//GEN-LAST:event_btnBAckMouseClicked

    private void btnRegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrationMouseEntered
        btnRegistration.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_btnRegistrationMouseEntered

    private void btnRegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrationMouseExited
        btnRegistration.setBackground(new Color(237,111,113));
    }//GEN-LAST:event_btnRegistrationMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgruondPanel;
    private javax.swing.JLabel btnBAck;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JPanel btnRegistration;
    private javax.swing.JLabel cellphone;
    private javax.swing.JLabel coperyng;
    private javax.swing.JLabel identifynumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel nacionaudiovisual;
    private javax.swing.JLabel name;
    private javax.swing.JLabel password;
    private javax.swing.JPanel scrollbar;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtCellphone;
    private javax.swing.JTextField txtDue;
    private javax.swing.JTextField txtIdentifyNumber;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtYearsold;
    private javax.swing.JLabel yearsold;
    // End of variables declaration//GEN-END:variables
}
