/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nacionaudiovisual.gui;

import java.awt.Color;

/**
 *
 * @author alexa
 */
public class students_login extends javax.swing.JFrame {

    /**
     * Creates new form students_login
     */
    
    int xMouse , yMouse;
    
    public students_login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnBack = new javax.swing.JPanel();
        txtBack = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        buttomLogin = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        toolMove = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name.setText("User Name");
        backgroundPanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        password.setText("Password");
        backgroundPanel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        txtUserName.setBackground(new java.awt.Color(255, 201, 201));
        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(102, 102, 102));
        txtUserName.setText("write your user name");
        txtUserName.setBorder(null);
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserNameMousePressed(evt);
            }
        });
        backgroundPanel.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 220, -1));

        btnBack.setBackground(new java.awt.Color(1, 75, 160));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBack.setForeground(new java.awt.Color(255, 255, 255));
        txtBack.setText("back");
        txtBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBack, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        backgroundPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        txtPassword.setBackground(new java.awt.Color(255, 201, 201));
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setText("**********");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        backgroundPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 220, 20));

        buttomLogin.setBackground(new java.awt.Color(1, 75, 160));
        buttomLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttomLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttomLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttomLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttomLoginMouseExited(evt);
            }
        });

        login.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");

        javax.swing.GroupLayout buttomLoginLayout = new javax.swing.GroupLayout(buttomLogin);
        buttomLogin.setLayout(buttomLoginLayout);
        buttomLoginLayout.setHorizontalGroup(
            buttomLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomLoginLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(login)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        buttomLoginLayout.setVerticalGroup(
            buttomLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        backgroundPanel.add(buttomLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nacionaudiovisual/imagesBackground/login_student.png"))); // NOI18N
        backgroundPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        toolMove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolMoveMouseDragged(evt);
            }
        });
        toolMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolMoveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout toolMoveLayout = new javax.swing.GroupLayout(toolMove);
        toolMove.setLayout(toolMoveLayout);
        toolMoveLayout.setHorizontalGroup(
            toolMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        toolMoveLayout.setVerticalGroup(
            toolMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        backgroundPanel.add(toolMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toolMoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolMoveMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_toolMoveMousePressed

    private void toolMoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolMoveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_toolMoveMouseDragged

    private void txtBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseClicked
        
        main_login backmain = new main_login();
        backmain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtBackMouseClicked

    private void txtBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseEntered
        //exitButtom.setBackground(Color.red);
        txtBack.setForeground(Color.red);
    }//GEN-LAST:event_txtBackMouseEntered

    private void txtBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseExited
        //exitButtom.setBackground(new Color(1,75,160));
        txtBack.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_txtBackMouseExited

    private void buttomLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttomLoginMouseEntered
        buttomLogin.setBackground(new Color(0,25,85));
        login.setForeground(Color.RED);
       
    }//GEN-LAST:event_buttomLoginMouseEntered

    private void buttomLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttomLoginMouseExited
        buttomLogin.setBackground(new Color(1,75,160));
        login.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_buttomLoginMouseExited

    private void txtUserNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMousePressed
        
        String textPass = "**********";
        String textUser = "write your user name";
        String tempPsss = String.valueOf(txtPassword.getPassword());
        if(txtUserName.getText().equals("") || txtUserName.getText().equals(textUser)){
            if(tempPsss.isEmpty() || tempPsss.equals(textPass)){
                txtPassword.setText("**********");
                txtUserName.setText("");
            }else{
            txtUserName.setText("");
            }
        }
        else{
            if(tempPsss.isEmpty() || tempPsss.equals(textPass)){
                txtPassword.setText("**********");
            }
        }
    }//GEN-LAST:event_txtUserNameMousePressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        String textPass = "**********";
        String textUser = "write your user name";
        
        String tempPsss = String.valueOf(txtPassword.getPassword());
        if(tempPsss.isEmpty() || tempPsss.equals(textPass)){
            if(txtUserName.getText().isEmpty() || txtUserName.getText().equals(textUser)){
                txtUserName.setText("write your user name");
                txtPassword.setText("");
            }
            else{
                txtPassword.setText("");
            }
        }
        else{
            if(txtUserName.getText().isEmpty() || txtUserName.getText().equals(textUser)){
                txtUserName.setText(textUser);
            }
        }
    }//GEN-LAST:event_txtPasswordMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel buttomLogin;
    private javax.swing.JLabel login;
    private javax.swing.JLabel name;
    private javax.swing.JLabel password;
    private javax.swing.JPanel toolMove;
    private javax.swing.JLabel txtBack;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
